### ISSUE TITLE
Unable to connect to acceess point 

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.setup#2]
On Raspberry Pi it was not possible to connect to the access point. The AP is visible, but the connection process hangs at the IP retrieval stage. Tested this with an Android phone (that had that issue also in the past using other APs) and my Mac (that never had that issue so far). The Wifi interface on the Pi was correctly configured and carried his own 10.0.0.1 IP.

**Comment by davidflanagan** [comment]
Please check that udhcpd is running and correctly configured. There are instructions in the readme about this. But also `sudo systemctl status udhcpd` should give information. If you can log in via a wired connection (or a serial connection) you should be able to observe what is going on while the device is in AP mode.

This worked for me in my testing so it may not be something I'm able to diagnose.  I've been testing from my macbook, though. I should try from a mobile phone as well.

**Comment by davidflanagan** [comment]
One of my most recent patches modified wifi.startAP() to behave differently on RPi and Edison. I may not have tested on RPi since I made that change. It should be running the same code as always, but maybe I broke something.  I'll check that

**Comment by davidflanagan** [comment]
This is a works for me issue. I can't fix it since I can't reproduce it.

In the first comment, however, you say:

> The Wifi interface on the Pi was correctly configured and carried his own 10.0.0.1 IP.

This means that even though you were not able to connect to the AP, you were logged in to the RPi. If you were using a wired ethernet connection, I think that might be interfering with the wifi process. If that was the case, please try again without the wired connection.

If you were using a serial connection to stay connected to the Pi while testing, it would be interesting to see the output of `sudo systemctl status udhcpd`. The symtom you describe would indicate that dhcpd is failing.

Oh wait! Andre recently noticed (and I recently fixed) an error in the README.md file where the intructions for copying the udhcpd.conf file were leaving out the second 'd' in 'udhcpd'. If you followed the directions exactly, you may not have the udhcpd.conf file configured correctly, and that would cause this bug.

**Comment by tilmankamp** [comment]
That was it.
