### ISSUE TITLE
Multiple network entries in wpa_supplicant.conf

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.setup#5]
Following the voice guided Wifi setup procedure, sometimes the voice confirms some action that was not taken yet - e.g. joining his network.
If things got messed up (in this context), `wpa_supplicant.conf` will contain several identical network entries, while `wlan0` is up with the correct SSID, but no IP.

**Comment by davidflanagan** [comment]
Can you give any more details? I'm not sure I understand.

Entries are added to wpa_supplicant.conf when the user clicks the connect button. If you click and go back and click again, I think that would cause multiple entries. I should see whether I can prevent that.  But it sounds like this bug is about more than just that.  (Could you have clicked the button more than once when you reported this?)

Are you doing this testing with a wired ethernet connection attached at the same time? I have not tested it that way, and don't know if it works.

Also, I've only tested on an RPi3. If you are using an RPi2, please tell me what wifi dongle you're using. Maybe there are hardware differences between our environments. 

Maybe attach the output of these commands?

```
$ iw list
$ iw features
```

I don't really understand any of that, but it would show us if we're using different wifi hardware
